"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var authsRouter_1 = require("./authsRouter");
var deploymentsRouter_1 = require("./deploymentsRouter");
var testsRouter_1 = require("./testsRouter");
var usersRouter_1 = require("./users/usersRouter");
var router = (0, express_1.Router)();
router.use('/users', usersRouter_1.default);
router.use('/auths', authsRouter_1.default);
router.use('/deployments', deploymentsRouter_1.default);
router.use('/tests', testsRouter_1.default);
exports.default = router;
